apiVersion: v1
appVersion: 7.0.1
description: Exporter for GitLab Prometheus metrics (e.g. CI, pull mirrors)
home: https://about.gitlab.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- gitlab
- gitlab-exporter
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: gitlab-exporter
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/gitlab-exporter
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-exporter
- https://gitlab.com/gitlab-org/gitlab-exporter
version: 3.3.1
