annotations:
  artifacthub.io/changes: |
    - Reorder HPA resource list to work with GitOps tooling
apiVersion: v1
appVersion: 0.41.2
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
engine: gotpl
home: https://github.com/kubernetes/ingress-nginx
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/61a46829-4e90-449b-9a0f-90b188e78028.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.16.0-0'
maintainers:
- name: ChiefAlexander
name: nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/nginx-ingress
version: 3.11.1
