apiVersion: v1
appVersion: 6.7.1
description: The leading tool for querying and visualizing time series and metrics.
engine: gotpl
home: https://grafana.net
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/e36ebf5a-40e6-422f-9ee0-b4fa29ab9cb3.png
kubeVersion: ^1.8.0-0
maintainers:
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rluckie@cisco.com
  name: rtluckie
- email: maor.friedman@redhat.com
  name: maorfr
name: grafana
sources:
- https://github.com/grafana/grafana
tillerVersion: '>=2.12.0'
version: 5.0.13
