apiVersion: v1
appVersion: 12.10.1
description: GitLab Geo logcursor
home: https://about.gitlab.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: geo-logcursor
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/geo-logcursor
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-rails
version: 3.3.1
