apiVersion: v1
appVersion: 13.7.1
description: Gitlab operator for managing upgrades
home: https://about.gitlab.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- gitlab
- operator
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: operator
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/operator
- https://gitlab.com/gitlab-org/charts/components/gitlab-operator
version: 4.7.1
