apiVersion: v1
appVersion: 13.7.0
description: GitLab Kubernetes Agent Server
home: https://about.gitlab.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- agent
- gitlab
- gitlab-kas
- k8s-agent
- kas
- kubernetes
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: kas
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/gitlab-kas
- https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
version: 4.7.1
