apiVersion: v1
appVersion: 13.7.1
description: Praefect is a router and transaction manager for Gitaly, and a required
  component for running a Gitaly Cluster.
home: https://about.gitlab.com/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/4c415edc-64eb-4faf-b132-83a288bce2f1.png
keywords:
- gitlab
- gitaly
- praefect
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: praefect
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/praefect
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitaly
- https://gitlab.com/gitlab-org/gitaly/-/tree/master/cmd/praefect
version: 4.7.1
